version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exam_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongPass123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db_data:/var/opt/mssql/data
      - ./db_backup:/var/opt/mssql/backup
